data:
  calls: calls.csv
  visitors: visitors.csv
  queries: queries.csv
output: prophet_output
model:
  seasonality_mode: multiplicative
  seasonality_prior_scale: 0.02
  holidays_prior_scale: 20
  changepoint_prior_scale: 0.1
  mcmc_samples: 0
  weekly_seasonality: true
  yearly_seasonality: true
  daily_seasonality: false
cross_validation:
  initial: '365 days'
  period: '30 days'
  horizon: '30 days'
