model:
  seasonality_mode: multiplicative
  additive_terms: ['event_dummies']
  seasonality_prior_scale: 10
  holidays_prior_scale: 20
  changepoint_prior_scale: 0.5
  mcmc_samples: 300
  weekly_seasonality: true
  yearly_seasonality: true
  daily_seasonality: false
cross_validation:
  initial: '180 days'
  period: '30 days'
  horizon: '60 days'
