data:
  calls: calls.csv
  visitors: visitors.csv
  queries: queries.csv
output: prophet_output
model:
  seasonality_mode: additive
  seasonality_prior_scale: 0.05
  holidays_prior_scale: 5
  changepoint_prior_scale: 0.05
  regressor_prior_scale: 0.05
  growth: linear
  mcmc_samples: 0
  weekly_seasonality: true
  yearly_seasonality: false
  daily_seasonality: false
cross_validation:
  initial: '270 days'
  period: '14 days'
  horizon: '30 days'
