data:
  calls: calls.csv
  visitors: visitors.csv
  queries: queries.csv
output: prophet_output
model:
  seasonality_mode: additive
  seasonality_prior_scale: 0.01
  holidays_prior_scale: 5
  changepoint_prior_scale: 0.05
  n_changepoints: 25
  changepoint_range: 0.9
  regressor_prior_scale: 0.05
  growth: logistic
  transform: log
  mcmc_samples: 0
  interval_width: 0.9
  weekly_seasonality: true
  yearly_seasonality: auto
  daily_seasonality: false
  likelihood: poisson
  weekly_incremental: true
  uncertainty_samples: 300
cross_validation:
  initial: '180 days'
  period: '30 days'
  horizon: '14 days'
